env:
  browser: false
  es2021: true
extends:
  - airbnb-base
  - prettier
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - prettier
rules:
  import/prefer-default-export: 0
  import/named: 0
  no-param-reassign: 0
  linebreak-style:
    - error
    - unix
  camelcase: 0
  max-len:
    - error
    - code: 200
  prettier/prettier:
    - warn
    - singleQuote: true
      semi: true
      trainlingComma: es5
  no-underscore-dangle:
    - error
    - allow:
        - _id
settings:
  import/resolver:
    babel-module: {}
